### ISSUE TITLE
LDC - the LLVM D compiler (6d3923):   based on DMD v2.066.1 and LLVM 3.5.0 fails

### ISSUE THREAD

**Issue by mroosmalen** [biod/BioD#13]
I tried to compile the create_bam_from_scratch.d script in the examples folder.

ldc2 examples/create_bam_from_scratch.d 

but it fails:

create_bam_from_scratch.o: In function `_Dmain':
examples/create_bam_from_scratch.d:(.text._Dmain+0x8): undefined reference to `_D3bio3sam6header9SamHeader7__ClassZ'
examples/create_bam_from_scratch.d:(.text._Dmain+0x16): undefined reference to `_D3bio3sam6header9SamHeader6__vtblZ'
etc.......
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1

**Comment by lomereiter** [comment]
The command line for compilation should be
```bash
rdmd --compiler=ldmd2 --build-only examples/create_bam_from_scratch.d
```
Think of `ldc2` as `g++`, and of `rdmd` as... let's say, `make` on steroids - in that you don't have to write an explicit `Makefile`.
