### ISSUE TITLE
accessing header?

### ISSUE THREAD

**Issue by lonestar21** [biod/BioD#14]
Hi all,
I was trying out the code you posted.  Its awesome!

I've tried writing my own simple application following some of the examples.    I'm wondering if there is a way to access the "@PG" lines of the header directly?

Right now I've set up a bam=new BamReader(...), and I can see that the header is available in bam.header.   However, looking through all the code it seems like the different parts of the header might be directly indexable. Is this possible?

thanks,
Richard

**Comment by lomereiter** [comment]
Hi Richard,

The access to header fields was quite inconvenient, indeed.
With the latest commit, the following code works as intended:
```d
import bio.sam.header, bio.bam.reader, std.stdio;    
                                                                 
void main(string[] args) {                                       
  auto header = new BamReader(args[1]).header;                   
                                                                 
  auto programs = header.programs;                               
  programs["GATK IndelRealigner"].program_version = "7.8.9";     
  writeln(header);                                               
}
```
