### ISSUE TITLE
BioD design document 

### ISSUE THREAD

**Issue by biorelated** [biod/BioD#15]
I was wondering,
1.  If there is a standard BioD development document in some form or another and if not do you think it makes sense to develop one or rather put is in a written form? 
2. What about having BioD development proposals? (BDDP)
   The purpose of a development proposal is akin to what the D community uses and I kind of feel it is a good way to discuss development proposals and elicit discussions.

**Comment by lomereiter** [comment]
1. There's none. Last year @pjotrp started to write some docs on internals of sambamba and, tangentially, BioD, but they are still more of a draft (https://github.com/lomereiter/sambamba-dev-docs). It would be nice to have one, but for me this is of low priority. If you want to help with this, I'd be thankful.

2. I don't see much point to it, at least right now. There's almost no community so far, and for the time being Github issues can serve as a place for discussions (such as this very one).

**Comment by biorelated** [comment]
1. I am happy to help!
2. I agree with using github issues for discussion. If people see more discussions and work around them, a community may emerge. There are 18 stars already which is a great nucleus for a community :)
