### ISSUE TITLE
output BAM chunk position for a given genomic interval using BAI

### ISSUE THREAD

**Issue by darked89** [biod/BioD#17]
Hello,

I would like to pinch out some BioD code to do the following:
given that I do have fasta reference and BAI file, I want to get start and end positions for a bgzf chunk. Something like regs2bins combined with parsing BAI file. I am able to access the data in BAI:
`import bio.bam.baifile;`
`import std.stdio;`
`void main() {`
`auto bai_fh = new BaiFile("./test.bam.bai");`
`writeln(bai_fh.indices);` 
`}`
but finding which Bin/Bins I need is another matter. I am just trying to start with D coming from Python.

The goal is to dump samtools/sambamba/picard compatible mini-BAM using either curl for a remote BAM or dd for a local one. 

Many thanks for your help

Darek Kedra

**Comment by lomereiter** [comment]
Hi Darek,
Could you please clarify what is it that you want?
Are you looking for something along [these lines](https://github.com/biod/BioD/blob/1eb4a6761e5d54c90577958a41729faf45414b35/bio/bam/randomaccessmanager.d#L220-L242)?

**Comment by darked89** [comment]
Hi Artem,

thank you for a prompt answer. In short: most likely, yes. But I need to read about OOP in D in order to use this method.
In the end I want to extract reads from small, ca 2x Illumina insert size regions (1200bp or so, at this stage one per file)  containing a point/small indel mutation. I hope that in most of the cases I should get all reads overlapping these 1200bp region (plus extra reads I will not need downstream) from a single BGZF block from the BAM. So if I get coffset for the BGZF block start, plus the end of the block, write this block to disk, I hope I can reconstruct from this mini-BAM gluing end of BAM file mark and BAM header. Or am I just badly confused about  BAM file structure?  

Many thanks for your help and patience.  

D.

**Comment by lomereiter** [comment]
Hi Darek,

It's not that easy, because reads are allowed to intersect block boundaries (although most software, including mine, tries to avoid this).
The proper way of tackling this would be to add a wrapper around `curl` library so that HTTP/FTP links can be handled as seekable streams. That's how it's done in `samtools`, and perhaps you should just use it, because your scenario doesn't take advantage of multithreading anyway.
