### ISSUE TITLE
module std.streams is deprecated

### ISSUE THREAD

**Issue by wilzbach** [biod/BioD#19]
... It will be removed from Phobos in October 2016.

**Comment by lomereiter** [comment]
I'm perfectly aware of the fact, compilers used to annoy me with this message until I started running them with `-d` flag. Since there's no replacement on the horizon, my preferred course of action would be to simply grab std.stream from undeaD repo. Better ideas are of course welcome.

**Comment by wilzbach** [comment]
> Better ideas are of course welcome.

There are already a couple more modern packages on dub that should be a better replacement - like e.g.:

- https://jasonwhite.github.io/io/
- https://github.com/schveiguy/iopipe
- ...
