### ISSUE TITLE
FASTA headers containing >

### ISSUE THREAD

**Issue by boulund** [biod/BioD#22]
Hi!

I was just glancing through the code, and noticed what I think might be an error in the FASTA parser. The way it's written right now, wouldn't it produce erroneous `FastaRecord`s if it encountered a FASTA header with the `>` character in it, e.g. like `>test header that was sampled at >3m depth in the ocean`? I haven't written any D code in several years, but it looks like there could be an issue there. Perhaps the fasta parser doesn't see much use?

All the best,
Fredrik

**Comment by lomereiter** [comment]
Hi, you are spot on. The proper way would be to split on `\n>`, I guess.
This parser is really a toy one, a real one wouldn't try to load the whole file into memory. Feel free to come up with PRs if you're interested.
