### ISSUE TITLE
undead.stream uses ulong instead of size_t for positions

### ISSUE THREAD

**Issue by tillea** [biod/BioD#27]
Hi,
I've just uploaded a fix for an [issue reported on Debian](https://bugs.debian.org/859688).  Feel free to take over the according [patch](https://anonscm.debian.org/cgit/debian-med/libbiod.git/tree/debian/patches/0016-fix-type-conversion.patch).
Kind regards, Andreas.

**Comment by pjotrp** [comment]
Thanks @tillea

**Comment by tillea** [comment]
Hi Pjotr,
On Tue, Apr 18, 2017 at 04:27:05AM -0700, Pjotr Prins wrote:
> Thanks @tillea 
You are welcome.  Do you plan a new release of libbiod soon?  Debian D maintainers suggested that this would be helpful.
