### ISSUE TITLE
stream.d unavailable

### ISSUE THREAD

**Issue by RichardCorbett** [biod/BioD#29]
Hi all,
admittedly I'm not very wise in the ways of D.     I tried to recompile some old code from sambamba but got the following error.  How do you recommend I fix this?
Should I start with a new sambamba download?
Find a different D compiler?
Any help would be appreciated.  
thanks,
Richard

....
rdmd --force --build-only -IBioD -g -L-Lhtslib -L-l:libhts.a -L-l:libphobos2.a -ofbuild/sambamba main.d
BioD/bio/bam/referenceinfo.d(26): Error: module stream is in file 'std/stream.d' which cannot be read

**Comment by lomereiter** [comment]
Hi Richard,

This module has been removed from standard library some time ago, and it seems you have outdated BioD git submodule. You should pull latest changes in both sambamba and BioD (run `git submodule update` for the latter) and also run `git clone https://github.com/dlang/undeaD`. See sambamba [compilation instructions](https://github.com/lomereiter/sambamba#compiling-sambamba).

**Comment by pjotrp** [comment]
More of a deployment/dub issue.
