### ISSUE TITLE
Bug in bio/core/utils/outbuffer.d: _heap.length is not correctly set

### ISSUE THREAD

**Issue by lh3** [biod/BioD#31]
In [line 82](https://github.com/lh3/BioD/blob/master/bio/core/utils/outbuffer.d#L82) of outbuffer.d, the current code is:
```cpp
capacity = _heap_capacity;
```
However, because `_heap_capacity` has been changed, in property `capacity()` ([line 68](https://github.com/lh3/BioD/blob/master/bio/core/utils/outbuffer.d#L68) at present), `_heap.length` is not updated. The quoted line above has no effect. Line 82 should be changed to:
```cpp
_heap.length = _heap_capacity;
```

**Comment by lomereiter** [comment]
Thanks for spotting the bug!
