### ISSUE TITLE
segmentation fault in examples/make_pileup

### ISSUE THREAD

**Issue by george-githinji** [biod/BioD#41]
`rdmd -I.. -I../../undeaD/src make_pileup.d`

returns a segmentation fault with DMD64 D Compiler v2.082.0

`[1]    3134 segmentation fault  rdmd -I.. -I../../undeaD/src make_pileup.d`

**Comment by pjotrp** [comment]
See #44. 

Can you make a stack trace with gdb? I run it as 

```sh
gdb -iex "handle SIGUSR1 SIGUSR2 nostop noprint" biod_test 
```

**Comment by george-githinji** [comment]
This issue seems to stem from a particular usage of assert statement. Removing the assert statement appears to resolve the issue. We need to investigate whether this is an upstream issue. I will suggest closing this issue for now.
