### ISSUE TITLE
Error: cannot implicitly convert expression

### ISSUE THREAD

**Issue by tillea** [biod/BioD#43]
Hi,
there is a [bug report](https://bugs.debian.org/912077) for the Debian packaged version.

    [77/177] ldc2 -I=biod@sha -I=. -I=.. -I/usr/include/d -enable-color -O -g -release -wi -relocation-model=pic   -of='biod@sha/bio2_bgzf.d.o' -c ../bio2/bgzf.d
    FAILED: biod@sha/bio2_bgzf.d.o
    ldc2 -I=biod@sha -I=. -I=.. -I/usr/include/d -enable-color -O -g -release -wi -relocation-model=pic   -of='biod@sha/bio2_bgzf.d.o' -c ../bio2/bgzf.d
    ../bio2/bgzf.d(214): Error: cannot implicitly convert expression `tuple(Nullable(0LU, true), compressed_buf, 0LU, crc32)` of type `Tuple!(Nullable!ulong, ubyte[], ulong,                immutable(uint))` to `Tuple!(Nullable!ulong, ubyte[], uint, immutable(uint))`

Any idea what might be wrong?

Kind regards, Andreas.

**Comment by pjotrp** [comment]
This is probably due to a compiler upgrade. Are you on ldc 1.12 now?

**Comment by tillea** [comment]
On Mon, Oct 29, 2018 at 05:01:27AM -0700, Pjotr Prins wrote:
> This is probably due to a compiler upgrade. Are you on ldc 1.12 now?
Current ldc in unstable is ldc 1.12.0 but the build log of the erroneous build (see link in bug report) mentions:

    Get:51 http://debian.csail.mit.edu/debian unstable/main i386 libphobos2-ldc-shared81 i386 1:1.11.0-2 [9456 kB]
    Get:52 http://debian.csail.mit.edu/debian unstable/main i386 libphobos2-ldc-shared-dev i386 1:1.11.0-2 [6160 kB]
    Get:53 http://debian.csail.mit.edu/debian unstable/main i386 libedit2 i386 3.1-20180525-1 [91.3 kB]
    Get:54 http://debian.csail.mit.edu/debian unstable/main i386 libllvm6.0 i386 1:6.0.1-9 [16.4 MB]
    Get:55 http://debian.csail.mit.edu/debian unstable/main i386 ldc i386 1:1.11.0-2 [2913 kB]

Kind regards, Andreas.

**Comment by pjotrp** [comment]
OK. I just installed 1.12. I need meson and dub to play on my system and see if I can crack this one.

**Comment by tillea** [comment]
On Fri, Jan 18, 2019 at 11:29:17AM -0800, Michael R. Crusoe wrote:
> I think you missed one:
I'm a bit in a hurry with real life.  In case you have a patch which solves the issue I have granted you upload permissions for libbiod.

**Comment by mr-c** [comment]
@tillea Oh, that was a comment for @pjotrp ; I've already added that to Debian's patch

**Comment by pjotrp** [comment]
I'll patch it. We'll work on BioD and sambamba the coming week.

**Comment by pjotrp** [comment]
New release compiles on Debian.
