### ISSUE TITLE
Build time failure

### ISSUE THREAD

**Issue by tillea** [biod/BioD#50]
Hi,
there is a [bug report](https://bugs.debian.org/917721) against the Debian packaged version of libbiod.  I can confirm that I can reproduce the issue locally.  Please see the [full build log here](https://bugs.debian.org/917721).  Unfortunately I have no idea how to fix this.
Kind regards, Andreas.

**Comment by tillea** [comment]
Hi @pjotrp , do you think you can solve this in the next couple of days?  Otherwise libbiod will not be part of the next Debian stable release.

**Comment by pjotrp** [comment]
@tillea that is OK. The only tool using libbiod is sambamba - and that won't go in either. I aim to fix stuff, but I have a lot of things right now to keep me from doing real work ;). I'll ping you when we have a reasonable build process for Debian a.o.

**Comment by pjotrp** [comment]
@tillea libbiod should compile and test on Debian recent.

**Comment by tillea** [comment]
On Tue, Nov 19, 2019 at 03:01:07AM -0800, Pjotr Prins wrote: > @tillea
libbiod should compile and test on Debian recent.  I confirm all the *.o
are compiled correctly and I also get bin/biod_tests.  However, the *.so
and *.a libraries are not build any more.  I remember your disagreement
with Matthias about providing the dynamic library - but that's how Debian
works.  So what's the best way to finally get sambamba which is my final
target?  Add a target to link the library to the makefile and link sambamba
to it would my prefered method.
Nice to see you here around, Andreas.

**Comment by pjotrp** [comment]
Are you using dub to build it or the Makefile?

**Comment by tillea** [comment]
On Tue, Nov 19, 2019 at 07:42:30AM -0800, Pjotr Prins wrote:
> Are you using dub to build it or the Makefile?
I'm using make - just learned about dub.  Should I use dub?
Is it just calling dub or some options?

**Comment by pjotrp** [comment]
I just fixed dub. Let me fix the makefile.

**Comment by pjotrp** [comment]
If I compile 

    make sharedlibrary
    make check

it passes and there is libbiod.so. Unfortunately the tests fail when I include debug information. It is probably not a great idea to release this until they are fixed.

**Comment by pjotrp** [comment]
Looks like it is the same out of order GC cleanup as we have in sambamba. At least I can duplicate that easily now. See also https://github.com/biod/sambamba/issues/393

**Comment by pjotrp** [comment]
@tillea try

    make sharedlibrary  
    make check

**Comment by tillea** [comment]
On Tue, Nov 19, 2019 at 10:17:24AM -0800, Pjotr Prins wrote:
> @tillea try
> 
>     make sharedlibrary  
>     make check

It would be convenient if you would add a new tag.  I only see 0.2.3.
Please tell me so if you want me to test latest HEAD before you tag.

Kind regards

     Andreas.

-- 
http://fam-tille.de

**Comment by pjotrp** [comment]
Try the HEAD. I don't want to create a range of releases just for debugging.

**Comment by tillea** [comment]
Hi Pjotr,

On Tue, Nov 19, 2019 at 09:03:14AM -0800, Pjotr Prins wrote:
> If I compile 
> 
>     make sharedlibrary

I confirm the *.so file is built.  However, the Debian libbiod-dev
package also contained libbiod.a which is not built any more.

>     make check

Works.
 
Do you see any chance to also create the static lib?

Kind regards

     Andreas.

-- 
http://fam-tille.de

**Comment by pjotrp** [comment]
Hmmm. This needs more work. I realise now that I should create a test setup that uses this library. I'll do this.

@tillea, you do realise you have to supply the D source tree too? They work like 'include' files in C and C++. Without them the D library will be pretty useless. It makes supplying a library pretty superfluous because most people will just include the sources (like you do in  Python and Ruby). Also, building the second way provides much better optimizations for the resulting binary.

Building a library is a useful exercise for biod. But there really is not much value for software distribution.

**Comment by tillea** [comment]
On Wed, Nov 20, 2019 at 02:49:58AM -0800, Pjotr Prins wrote:
> Hmmm. This needs more work. I realise now that I should create a test setup that uses this library. I'll do this.
> 
> @tillea, you do realise you have to supply the D source tree too? They work like 'include' files in C and C++. Without them the D library will be pretty useless. It makes supplying a library pretty superfluous because most people will just include the sources (like you do in  Python and Ruby). Also, building the second way provides much better optimizations for the resulting binary.
> 
> Building a library is a useful exercise for biod. But there really is not much value for software distribution.

Seems we are in the same "ping-pong"-situation with Matthias (in CC) again.  I'm perfectly fine with whatever brings me a working sambamba and is not in conflict with any language policy in Debian.  Any hints how to approach this is really welcome.
@Matthias: Packaging Git has latest upstream HEAD.  If you mind having a look - in the best case implementing what Pjotr suggests - I'd be really happy.  As I said: I need a working sambamba executable (most preferably not significantly slower than a manually / conda compiled one).
Kind regards, Andreas.

**Comment by pjotrp** [comment]
On the sambamba side I need to fix the threading bug that has been haunting us since ldc 1.10 or so. libbiod is part of that problem. Maybe better keep this on hold again.
